version: 2
project_name: syftbox
dist: .out

before:
  hooks:
  - go mod tidy

builds:
- id: syftbox_client
  binary: syftbox
  main: ./cmd/client
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -linkmode 'external'
  - -extldflags '-static'
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version=0.5.0
  tags:
  - sonic # for gin with sonic json
  - avx # for sonic
  - sqlite_omit_load_extension # for sqlite3
  env:
  - CGO_ENABLED=1
  - CGO_CFLAGS=-Ofast
  - >-
    {{- if eq .Os "linux" }}
      {{- if eq .Arch "amd64" }}CC=x86_64-linux-musl-gcc{{- end }}
      {{- if eq .Arch "arm64"}}CC=aarch64-linux-musl-gcc{{- end }}
    {{- end }}
  - >-
    {{- if eq .Os "linux" }}
      {{- if eq .Arch "amd64" }}CXX=x86_64-linux-musl-g++{{- end }}
      {{- if eq .Arch "arm64"}}CXX=aarch64-linux-musl-g++{{- end }}
    {{- end }}
  goos:
  - linux
  goarch:
  - amd64
  - arm64

- id: syftbox_client_windows
  binary: syftbox
  main: ./cmd/client
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version=0.5.0
  tags:
  - sonic # for gin with sonic json
  - avx # for sonic
  - sqlite_omit_load_extension # for sqlite3
  env:
  - CGO_ENABLED=1
  - >-
    {{- if eq .Os "windows" }}
      {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
    {{- end }}
  - >-
    {{- if eq .Os "windows" }}
      {{- if eq .Arch "amd64" }}CXX=x86_64-w64-mingw32-g++{{- end }}
    {{- end }}
  goos:
  - windows
  goarch:
  - amd64
  # - arm64

- id: syftbox_client_macos
  binary: syftbox
  main: ./cmd/client
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version=0.5.0
  tags:
  - sonic # for gin with sonic json
  - avx # for sonic
  - sqlite_omit_load_extension # for sqlite3
  env:
  - CGO_ENABLED=1
  goos:
  - darwin
  goarch:
  - amd64
  - arm64

- id: syftbox_server
  binary: syftbox_server
  main: ./cmd/server
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -linkmode 'external'
  - -extldflags '-static'
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version=0.5.0
  tags:
  - sonic # for gin with sonic json
  - avx # for sonic
  - sqlite_omit_load_extension # for sqlite3
  env:
  - CGO_ENABLED=1
  - CGO_CFLAGS=-Ofast
  - >-
    {{- if eq .Os "linux" }}
      {{- if eq .Arch "amd64" }}CC=x86_64-linux-musl-gcc{{- end }}
      {{- if eq .Arch "arm64"}}CC=aarch64-linux-musl-gcc{{- end }}
    {{- end }}
  - >-
    {{- if eq .Os "linux" }}
      {{- if eq .Arch "amd64" }}CXX=x86_64-linux-musl-g++{{- end }}
      {{- if eq .Arch "arm64"}}CXX=aarch64-linux-musl-g++{{- end }}
    {{- end }}
  goos:
  - linux
  goarch:
  - amd64
  - arm64

# binary_signs:
# - id: macos-sign
#   artifacts: binary
#   ids:
#   - syftbox_client_macos
#   cmd: codesign
#   args: [ "--verbose", "--force", "--deep", "--verify", "--timestamp", "--options", "runtime", "--sign", "Developer ID Application: OpenMined Foundation (28PJ5N8D9X)", "${artifact}" ]
#   output: true

archives:
- id: client
  name_template: "syftbox_client_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  ids:
  - syftbox_client
  - syftbox_client_macos
  - syftbox_client_windows
  format_overrides:
  - goos: windows
    formats: [ zip ]

- id: server
  name_template: "syftbox_server_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  ids:
  - syftbox_server

checksum:
  name_template: 'checksums.txt'

report_sizes: true
