version: 2
project_name: syftbox
dist: .out

before:
  hooks:
  - go mod tidy

builds:
- id: syftbox_client
  binary: syftbox
  main: ./cmd/client
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version={{.RawVersion}}
  tags:
  - go_json # gin: use goccy/go-json
  - nomsgpack # gin: disable msgpack
  env:
  - CGO_ENABLED=0 # rjeczalik/notify on linux/windows doesn't need CGO
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64

- id: syftbox_client_macos
  binary: syftbox
  main: ./cmd/client
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version={{.Version}}
  tags:
  - go_json # gin: use goccy/go-json
  - nomsgpack # gin: disable msgpack
  env:
  - CGO_ENABLED=1 # rjeczalik/notify needs CGO for fsevents on darwin
  goos:
  - darwin
  goarch:
  - amd64
  - arm64

- id: syftbox_server
  binary: syftbox_server
  main: ./cmd/server
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -X github.com/openmined/syftbox/internal/version.Revision={{.ShortCommit}}
  - -X github.com/openmined/syftbox/internal/version.BuildDate={{.Date}}
  - -X github.com/openmined/syftbox/internal/version.Version={{.Version}}
  tags:
  - sonic # gin: use bytedance/sonic
  - avx # gin: required to enable sonic
  - nomsgpack # gin: disable msgpack
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm64 # sonic won't work https://github.com/gin-gonic/gin/pull/4234

# temporary disable signing for macos amd64 CODESIGN_FAILED. needs investigation.
# binary_signs:
# - id: macos-sign
#   artifacts: binary
#   ids:
#   - syftbox_client_macos
#   cmd: codesign
#   args: [ "--verbose", "--force", "--deep", "--verify", "--timestamp", "--options", "runtime", "--sign", "Developer ID Application: OpenMined Foundation (28PJ5N8D9X)", "${artifact}" ]
#   output: true

archives:
- id: client
  name_template: "syftbox_client_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  ids:
  - syftbox_client
  - syftbox_client_macos
  format_overrides:
  - goos: windows
    formats: [ zip ]

- id: server
  name_template: "syftbox_server_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  ids:
  - syftbox_server

checksum:
  name_template: checksums.txt

report_sizes: true
