http:
  address: 127.0.0.1:8080

blob:
  bucket_name: syftbox-local
  region: us-east-1
  endpoint: http://localhost:9000
  access_key: ptSLdKiwOi2LYQFZYEZ6
  secret_key: GMDvYrAhWDkB2DyFMn8gU8I8Bg0fT3JGT6iEB7P8

auth:
  enabled: false # <--!!!
  token_issuer: http://127.0.0.1:8080
  refresh_token_secret: refresh_token_secret
  refresh_token_expiry: 0
  access_token_secret: access_token_secret
  access_token_expiry: 72h
  email_addr: test@example.com
  email_otp_length: 8
  email_otp_expiry: 5m
